FROM node:20-alpine AS builder
WORKDIR /app

ARG VITE_GRAPHQL_HTTP_URL
ARG VITE_GRAPHQL_WS_URL
ARG VITE_V3_LOGIN
ARG VITE_V3_PSWD
ARG VITE_USE_MOCK=false
ARG VITE_EMPRESA
ARG VITE_SUCURSAL
ARG VITE_GRAPHQL_TOKEN

ENV VITE_GRAPHQL_HTTP_URL=$VITE_GRAPHQL_HTTP_URL
ENV VITE_GRAPHQL_WS_URL=$VITE_GRAPHQL_WS_URL
ENV VITE_V3_LOGIN=$VITE_V3_LOGIN
ENV VITE_V3_PSWD=$VITE_V3_PSWD
ENV VITE_USE_MOCK=$VITE_USE_MOCK
ENV VITE_EMPRESA=$VITE_EMPRESA
ENV VITE_SUCURSAL=$VITE_SUCURSAL
ENV VITE_GRAPHQL_TOKEN=$VITE_GRAPHQL_TOKEN

COPY package*.json ./
RUN npm ci
RUN npm install --no-save @rollup/rollup-linux-x64-musl

COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
