import { normalizeComanda } from "./comandas";

const now = Date.now();

const mockComandasRaw = [
  {
    id: "1",
    codigo: "CMD-1001",
    canal: "whatsapp",
    clienteNombre: "Ana Pérez",
    clienteTelefono: "809-555-1001",
    tipoEntrega: "delivery",
    direccionEntrega: "Calle 1, Ensanche Naco",
    referenciaDireccion: "Frente al parque",
    estado: "pendiente",
    estadoPago: "pendiente",
    metodoPago: "transferencia",
    referenciaPago: "",
    subtotal: 550,
    costoDelivery: 100,
    total: 650,
    observacion: "Sin cebolla",
    empresa: "icarosoft",
    sucursal: "naco",
    createdAt: new Date(now - 3 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 3 * 60 * 1000).toISOString(),
    isNew: true,
    detalles: [
      {
        id: "1-1",
        productoNombre: "Hamburguesa clásica",
        cantidad: 2,
        precio: 250,
        total: 500,
        observacion: "Termino medio",
      },
      {
        id: "1-2",
        productoNombre: "Refresco",
        cantidad: 1,
        precio: 50,
        total: 50,
        observacion: "",
      },
    ],
  },
  {
    id: "2",
    codigo: "CMD-1002",
    canal: "web",
    clienteNombre: "Luis Gómez",
    clienteTelefono: "809-555-1002",
    tipoEntrega: "pickup",
    estado: "pagada",
    estadoPago: "pagado",
    metodoPago: "tarjeta",
    referenciaPago: "TRX9982",
    subtotal: 400,
    costoDelivery: 0,
    total: 400,
    empresa: "icarosoft",
    sucursal: "naco",
    createdAt: new Date(now - 12 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 7 * 60 * 1000).toISOString(),
    detalles: [
      {
        id: "2-1",
        productoNombre: "Pizza personal",
        cantidad: 1,
        precio: 400,
        total: 400,
        observacion: "Extra queso",
      },
    ],
  },
  {
    id: "3",
    codigo: "CMD-1003",
    canal: "whatsapp",
    clienteNombre: "María Díaz",
    clienteTelefono: "809-555-1003",
    tipoEntrega: "delivery",
    estado: "lista",
    estadoPago: "pagado",
    metodoPago: "efectivo",
    subtotal: 700,
    costoDelivery: 120,
    total: 820,
    direccionEntrega: "Av. Winston Churchill",
    referenciaDireccion: "Edificio azul",
    empresa: "icarosoft",
    sucursal: "piantini",
    createdAt: new Date(now - 42 * 60 * 1000).toISOString(),
    updatedAt: new Date(now - 10 * 60 * 1000).toISOString(),
    detalles: [
      {
        id: "3-1",
        productoNombre: "Wrap de pollo",
        cantidad: 2,
        precio: 350,
        total: 700,
        observacion: "",
      },
    ],
  },
];

export const MOCK_COMANDAS = mockComandasRaw.map(normalizeComanda);
